# Site
name: "Linuxera"
description: "Linux, Containers and Open Source"
meta_description: "linux, containers, openshift, kubernetes, k8s, ocp, okd, origin, redhat, centos, operators, controllers, golang, python"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
url: "https://linuxera.org"
google_analytics: 'UA-52346410-3'
disqus: 'linuxera'
mailchimp-list: ''

# Authors
authors:
  Mario:
    name: Mario
    display_name: Mario
    gravatar: 3fe66e316762f0efa028dab07ea2949f
    email: mario@linuxera.org
    twitter: https://twitter.com/mvazce
    description: Systems Engineer working on PaaS and Containers
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
